# Generated by Django 2.2.1 on 2019-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalPlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=40)),
                ('Image', models.ImageField(upload_to='Cultural_Places_Image')),
                ('Details', models.TextField(max_length=120)),
                ('ExtraContent', models.TextField(default='Null', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cultural Place Info',
            },
        ),
        migrations.CreateModel(
            name='CulturalPlaceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading1', models.CharField(max_length=50)),
                ('Heading2', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Title For Cultural Place',
            },
        ),
        migrations.CreateModel(
            name='NaturalPlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=40)),
                ('Image', models.ImageField(upload_to='Cultural_Places_Image')),
                ('Details', models.TextField(max_length=120)),
                ('ExtraContent', models.TextField(default='Null', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Natural Place Info',
            },
        ),
        migrations.CreateModel(
            name='NaturalPlaceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading1', models.CharField(max_length=50)),
                ('Heading2', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Title For Natural Place',
            },
        ),
    ]
