# Generated by Django 2.2.1 on 2019-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalplacedetails',
            name='Details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='naturalplacedetails',
            name='Details',
            field=models.TextField(max_length=500),
        ),
    ]
