# Generated by Django 2.2.1 on 2019-08-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null='True')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image1', models.ImageField(blank='True', upload_to='Blog_Photos')),
                ('image2', models.ImageField(blank='True', upload_to='Blog_Photos')),
                ('image3', models.ImageField(blank='True', upload_to='Blog_Photos')),
                ('image4', models.ImageField(blank='True', upload_to='Blog_Photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
