# Generated by Django 2.2.1 on 2019-06-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='our',
            options={'verbose_name_plural': 'Our Motto'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team'},
        ),
    ]
