# Generated by Django 2.2.1 on 2019-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyContent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Body_Title',
            },
        ),
        migrations.CreateModel(
            name='BodyContent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Body Text',
            },
        ),
        migrations.CreateModel(
            name='FirstContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text1', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'First Text Over Image',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Places', models.TextField(max_length=500)),
                ('Prices', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(default=' ', max_length=15)),
                ('Place', models.CharField(default=' ', max_length=20)),
                ('Image', models.ImageField(upload_to='Popular_Destination')),
            ],
            options={
                'verbose_name_plural': 'Images of Popular Destination',
            },
        ),
        migrations.CreateModel(
            name='SecondContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Second Context Over Image',
            },
        ),
        migrations.CreateModel(
            name='ThirdContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text3', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Third Context Over Image',
            },
        ),
    ]
