# Generated by Django 2.2.1 on 2019-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardestination',
            name='Place',
            field=models.CharField(default='DEFAULT VALUE ', max_length=20),
        ),
        migrations.AlterField(
            model_name='populardestination',
            name='Price',
            field=models.CharField(default='DEFAULT VALUE ', max_length=15),
        ),
    ]
