# Generated by Django 2.2.1 on 2019-06-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190609_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Title For Our Service Area',
            },
        ),
        migrations.CreateModel(
            name='OurService2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sub-Title For Our Service Area',
            },
        ),
        migrations.CreateModel(
            name='OurServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Details', models.TextField(max_length=250)),
                ('Content', models.ImageField(upload_to='Services')),
            ],
            options={
                'verbose_name_plural': 'Contents to Our Service Area',
            },
        ),
    ]
