# Generated by Django 2.2.1 on 2019-06-09 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ourservice1_ourservice2_ourserviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=200)),
                ('Descriptions', models.TextField(max_length=300)),
                ('Image', models.ImageField(upload_to='QuestionImage')),
                ('Button', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Question Asking Division',
            },
        ),
        migrations.CreateModel(
            name='OurPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=50)),
                ('Details', models.TextField(max_length=150)),
                ('Image', models.ImageField(upload_to='Famous_Places')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': ' Our Popular Places ',
            },
        ),
    ]
