# Generated by Django 2.2.1 on 2019-06-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homequestion_ourplaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstcontent',
            options={'verbose_name_plural': 'First Context Over Image'},
        ),
    ]
