# Generated by Django 2.2.1 on 2019-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190812_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='populardestination',
            name='Image5',
            field=models.ImageField(blank=True, upload_to='near_by_place'),
        ),
        migrations.AddField(
            model_name='populardestination',
            name='Image6',
            field=models.ImageField(blank=True, upload_to='near_by_place'),
        ),
        migrations.AddField(
            model_name='populardestination',
            name='Place5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='populardestination',
            name='Place6',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
